# Copyright (c) 2022, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.wso2.apk.dp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-cc-enforcer-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.wso2.apk.dp.cc.enforcer.deployment.replicas }}
  strategy:
    type: {{ .Values.wso2.apk.dp.cc.enforcer.deployment.strategy }}
  selector:
    matchLabels:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.dp.cc.enforcer.appName ) | indent 6}}
  template:
    metadata:
      labels:
        networkPolicyId: {{ .Values.wso2.apk.dp.cc.enforcer.deployment.npi }}
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.dp.cc.enforcer.appName ) | indent 8}}
    spec:
      containers:
        - name: cc-enforcer
          image: {{ .Values.wso2.apk.dp.cc.enforcer.deployment.image }}
          imagePullPolicy: {{ .Values.wso2.apk.dp.cc.enforcer.deployment.imagePullPolicy }}
          ports:
            - containerPort: 8081
              protocol: "TCP"
            - containerPort: 9001
              protocol: "TCP"
{{ include "apk-helm.deployment.resources" .Values.wso2.apk.dp.cc.enforcer.deployment.resources | indent 10 }}
{{ include "apk-helm.deployment.env" .Values.wso2.apk.dp.cc.enforcer.deployment.env | indent 10 }}
          volumeMounts:
            - name: cc-enforcer-keystore-secret-volume
              mountPath: /home/wso2/security/keystore
            - name: cc-enforcer-truststore-secret-volume
              mountPath: /home/wso2/security/truststore
            - name: cc-log-conf-volume
              mountPath: /home/wso2/conf/
      volumes: 
        - name: cc-enforcer-keystore-secret-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-cc-enforcer-keystore-secret
        - name: cc-enforcer-truststore-secret-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-cc-enforcer-truststore-secret
        - name: cc-log-conf-volume
          configMap: 
            name: {{ template "apk-helm.resource.prefix" . }}-cc-log-conf
{{- end -}}
