apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: petstore
  version: 1.0.6
spec:
  parentRefs:
  - name: eg
  hostnames:
  - www.example.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /user/logout
    - path:
        type: PathPrefix
        value: /pet
    - path:
        type: PathPrefix
        value: /pet/findByTags
    - path:
        type: PathPrefix
        value: /store/order/{orderId}
    - path:
        type: PathPrefix
        value: /user
    - path:
        type: PathPrefix
        value: /user/{username}
    - path:
        type: PathPrefix
        value: /pet/findByStatus
    - path:
        type: PathPrefix
        value: /store/inventory
    backendRefs:
    - name: httpbin
      port: 80
      group: ""
      kind: Service
