//  Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
//
//  WSO2 Inc. licenses this file to you under the Apache License,
//  Version 2.0 (the "License"); you may not use this file except
//  in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing,
//  software distributed under the License is distributed on an
//  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//  KIND, either express or implied.  See the License for the
//  specific language governing permissions and limitations
//  under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: wso2/discovery/api/Resource.proto

package oasparser

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resource struct {
	path                string
	methods             []*Operation
	description         string
	summary             string
	iD                  string
	// productionEndpoints *EndpointCluster
	// sandboxEndpoints    *EndpointCluster
	vendorExtensions    map[string]interface{}
	hasPolicies         bool
}

// Operation model which maps to a particular http methods
type Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method          string             `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Security        []*SecurityList    `protobuf:"bytes,2,rep,name=security,proto3" json:"security,omitempty"`
	Tier            string             `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	DisableSecurity bool               `protobuf:"varint,4,opt,name=disableSecurity,proto3" json:"disableSecurity,omitempty"`
	Policies        *OperationPolicies `protobuf:"bytes,5,opt,name=policies,proto3" json:"policies,omitempty"`
	MockedApiConfig *MockedApiConfig   `protobuf:"bytes,6,opt,name=mockedApiConfig,proto3" json:"mockedApiConfig,omitempty"`
}

// OperationPolicies holds policies of the APIM operations
type OperationPolicies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  []*Policy `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
	Response []*Policy `protobuf:"bytes,2,rep,name=response,proto3" json:"response,omitempty"`
	Fault    []*Policy `protobuf:"bytes,3,rep,name=fault,proto3" json:"fault,omitempty"`
}

type Policy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action     string            `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Parameters map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

type MockedApiConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*MockedResponseConfig `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty"`
}

type MockedResponseConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Headers []*MockedHeaderConfig  `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	Content []*MockedContentConfig `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
}

type MockedHeaderConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

type MockedContentConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType string                  `protobuf:"bytes,1,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Examples    []*MockedContentExample `protobuf:"bytes,2,rep,name=examples,proto3" json:"examples,omitempty"`
}

type MockedContentExample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref  string `protobuf:"bytes,1,opt,name=Ref,proto3" json:"Ref,omitempty"`
	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}