//  Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
//
//  WSO2 Inc. licenses this file to you under the Apache License,
//  Version 2.0 (the "License"); you may not use this file except
//  in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing,
//  software distributed under the License is distributed on an
//  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//  KIND, either express or implied.  See the License for the
//  specific language governing permissions and limitations
//  under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: wso2/discovery/api/security_scheme.proto

package oasparser

import (
	// protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	// reflect "reflect"
	// sync "sync"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecurityScheme config model
type SecurityScheme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefinitionName string `protobuf:"bytes,1,opt,name=definitionName,proto3" json:"definitionName,omitempty"` // name used to define security scheme
	Type           string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                     // type of the security scheme
	Name           string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                     // name of the security scheme
	In             string `protobuf:"bytes,4,opt,name=in,proto3" json:"in,omitempty"`                         // location of the API key in request
}

// func (x *SecurityScheme) Reset() {
// 	*x = SecurityScheme{}
// 	if protoimpl.UnsafeEnabled {
// 		mi := &file_wso2_discovery_api_security_scheme_proto_msgTypes[0]
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		ms.StoreMessageInfo(mi)
// 	}
// }

// func (x *SecurityScheme) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*SecurityScheme) ProtoMessage() {}

// func (x *SecurityScheme) ProtoReflect() protoreflect.Message {
// 	mi := &file_wso2_discovery_api_security_scheme_proto_msgTypes[0]
// 	if protoimpl.UnsafeEnabled && x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use SecurityScheme.ProtoReflect.Descriptor instead.
// func (*SecurityScheme) Descriptor() ([]byte, []int) {
// 	return file_wso2_discovery_api_security_scheme_proto_rawDescGZIP(), []int{0}
// }

// func (x *SecurityScheme) GetDefinitionName() string {
// 	if x != nil {
// 		return x.DefinitionName
// 	}
// 	return ""
// }

// func (x *SecurityScheme) GetType() string {
// 	if x != nil {
// 		return x.Type
// 	}
// 	return ""
// }

// func (x *SecurityScheme) GetName() string {
// 	if x != nil {
// 		return x.Name
// 	}
// 	return ""
// }

// func (x *SecurityScheme) GetIn() string {
// 	if x != nil {
// 		return x.In
// 	}
// 	return ""
// }

// Represents a single security array item applied at the API level or the API operation level
type SecurityList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScopeList map[string]*Scopes `protobuf:"bytes,1,rep,name=scopeList,proto3" json:"scopeList,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

// Holds the list of scopes belongs to a particular security schema
type Scopes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scopes []string `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
}